#!/bin/bash


function LogCon() {
echo "auth,authpriv.*@172.16.200.10:1514;RYSYLOG_SyslogProtocol23Format" >> etc/rsyslog.d/sec350.conf
systemctl restart rsyslog
}
function nginx() {
apt install nginx -Y
ufw allow 'Nginx HTTP'
ufw disable
ufw enable
echo "
<html>
<head>
<title>Internal Script</title>
</head>
<body>
<h1>
   Henry is great
</h1>
</body>
</html>
" >> /var/www/html/index.html
systemtctl restart nginx
}
SysCon
UserCon
NetCon
LogCon
nginx
